# 1. ?????????? 6GB?????? GC
org.gradle.jvmargs=-Xmx6g -XX:+UseParallelGC -Dfile.encoding=UTF-8 -Dsun.io.useCanonicalCaches=true

# 2. ???????????Mac M3 ???????????
org.gradle.vfs.watch=true

# 3. ??????????? M3 ??????
org.gradle.parallel=true

# 4. ?????????????????
org.gradle.caching=true

# 5. ??????????????? Module?????????
org.gradle.configureondemand=true

# ====================================================================
# Kotlin / Kapt ??
# ====================================================================
kotlin.incremental=true
kapt.use.worker.api=true
kapt.incremental.apt=true

# ====================================================================
# Android ??????
# ====================================================================
android.useAndroidX=true
android.enableJetifier=true
android.nonTransitiveRClass=true

# ====================================================================
# ?????????
# ====================================================================
systemProp.http.connectionTimeout=60000
systemProp.http.socketTimeout=60000